// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'firebase_options.dart';
/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = const FirebaseOptions(
    apiKey: 'AIzaSyDwoBfw9J7rSfDQgzNVJATD1CUo_Bm8lxg',
    appId: '1:1035277382998:web:e7159b92dbc2c2d38912f7',
    messagingSenderId: '1035277382998',
    projectId: 'flutter-corse-f0bb8',
    authDomain: 'flutter-corse-f0bb8.firebaseapp.com',
    storageBucket: 'flutter-corse-f0bb8.appspot.com',
    measurementId: 'G-ZRZ39RQJYG',
  );

  static FirebaseOptions android = const FirebaseOptions(
    apiKey: 'AIzaSyBlmRPufg6VoA6OOIQQWUQfQ84fxKiqeM8',
    appId: '1:1035277382998:android:23fa684ba67c08d18912f7',
    messagingSenderId: '1035277382998',
    projectId: 'flutter-corse-f0bb8',
    storageBucket: 'flutter-corse-f0bb8.appspot.com',
  );

  static FirebaseOptions ios = const FirebaseOptions(
    apiKey: 'AIzaSyBs0f7ABhi7Q_DSvTXCtru1JvJBZAXjtas',
    appId: '1:1035277382998:ios:18f8781ed26dabb58912f7',
    messagingSenderId: '1035277382998',
    projectId: 'flutter-corse-f0bb8',
    storageBucket: 'flutter-corse-f0bb8.appspot.com',
    iosClientId: '1035277382998-rnmdv57osf7p1qrddjr3f9gblqicv3gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWorkGoogleCourse',
  );

  static FirebaseOptions macos = const FirebaseOptions(
    apiKey: 'AIzaSyBs0f7ABhi7Q_DSvTXCtru1JvJBZAXjtas',
    appId: '1:1035277382998:ios:18f8781ed26dabb58912f7',
    messagingSenderId: '1035277382998',
    projectId: 'flutter-corse-f0bb8',
    storageBucket: 'flutter-corse-f0bb8.appspot.com',
    iosClientId: '1035277382998-rnmdv57osf7p1qrddjr3f9gblqicv3gi.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseWorkGoogleCourse',
  );
}
